# Generated by Django 4.0.4 on 2022-04-16 00:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('matricula', models.CharField(max_length=8, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('status_pendencia', models.BooleanField(editable=False)),
                ('status_ativo', models.BooleanField(editable=False)),
            ],
        ),
    ]
