# Generated by Django 4.0.4 on 2022-04-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_ativo',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_pendencia',
            field=models.BooleanField(editable=False),
        ),
    ]
