# Generated by Django 4.0.4 on 2022-04-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_cpf_alter_aluno_status_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status_ativo',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_pendencia',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
